[project]
name = "dvc-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dvc>=3.65.0",
    "omegaconf>=2.3.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
]
